const companies = [
  'Timmerbedrijf Zomerdijk',
  'Ten Brinke bestrating',
  'Loonbedrijf Heyblok',
  'Wieringer Viskoerier',
  'Fotograaf Kenneth Stamp',
  'Het Huis van de Wadden',
  'Betacore',
  'Rob Makreel',
  'Melvin Garneel',
  'DJ High Value',
  'Boer Rotgans',
  'Bert Boontjes',
  'Gemeente Hollands Kroon',
  'Buurtvereniging Noordervenne',
  'Buurtvereniging Klufterkrocht',
  'Wieringer Visbak team',
  'Wieringer garnalen kroket',
  'Bakker stofferingen',
  'Garage Klein',
  'Kleimeer assurantien',
  'NH 1816',
  'CIV Den Oever',
  'Cafe tante Pietje',
  'Detectie specialist D.J. Laan',
  'Kunstenaar Krin Rinsema',
  'Djestiek',
  'Figuranten groep OuderwetZ',
  'R. Jorna Visserijbedrijf',
  'Kringloopwinkel Twice',
  'HGO',
  'Eclectic Lighting BV',
  'P. Smit BV',
  'Stucadoorsbedrijf N. Hak en W. vd Schuur',
  'P. Klein Montage',
  'Sportvisserij Mercuur',
  'Nelon BV',
  'Hubo Anna Paulowna',
  'Jac Schouten Metselwerken',
  'Sandfirden Technics',
  'Poffertjes van Jan',
  'Kaan Transport',
  'Bluefood centrum',
  'Selie Transport',
  'Viking reclame',
  'Deka Den Oever',
  'Boer Niels van Duin',
  'Opkickertje',
  'CIV Den oever Binnenvisserij',
  'Loonbedrijf De Jongh',
  'Fruitkwekerij Het Keetje, Lutjebroek',
  'Drukkerij Burghout',
  'Microsoft/HKUD',
  'Zin in Oosterland/Michäelskerk',
  'G en G Visserijbedrijf BV',
  'Van Erp brandbeveiliging',
  'Bouwkundig Buro Sijnesael & van Wijck'
]

export default companies
