const companies = [
  'B&B het Huis van de Wadden',
  'Rotery Wieringerland',
  'Kleimeer Assurantiën',
  'Noord Hollandse 1816',
  'Hollands Kroonse uitdaging',
  'Rabobank Kop van Noord Holland',
  'Drukkerij Burghout',
  'CIV Den Oever',
  'Derk Kleimeer',
  'Rene Bakker stofferingen',
  'ROVE horeca groothandel',
  'Unive Noord Holland',
  'DJ High Values',
  'Holland Graphic Occasions',
  'Cafe Arlette',
  'Snippe riool techniek',
  'De Wieringer ijs- en Zuivelboerderij',
  'Slagerij Piet Ottens',
  'Buurtvereniging Noordervenne',
  'Zwembed de Venne',
  'Buurtvereniging Klufterkrogt',
  "Can's Fruit",
  'Wantij trio ',
  "Vis centrum 'Twad",
  'Museum Boerderij Jan Lont',
  'Kaan Transport BV',
  'Tijsen electrotechniek VOF',
  'Dans groep Parlan',
  'Visafslag Den Oever',
  'Gemeente Hollands Kroon',
  'Scouting Corvus Corone',
  'Voetbal vereniging Wiron',
  'Boer Rotgans',
  'Trijn Mulder',
  'Michaelskerk',
  'Ron Schirmann',
  'Team Sportservice Noordkop',
  'Loonbedrijf De Jongh',
  'Wieringer Visbak Team',
  'Pro Electro',
  'Photobooth West Friesland',
  'Van Erp brandbeveiliging',
  'Bert de Haan',
  'Alle vrijwilligers',
  'Alle bewoners langs de route',
  'All Inn verhuur',
  'Vader Verhuur'
]

export default companies
